version: '3'

services:

  server:
    build:
      #dockerfile location 
      context: server
    container_name: server
    networks:
      - node-network
    volumes: 
      - ./server:/var/www/node
    tty: true
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  db:
    #fix to mac m1
    platform: linux/x86_64
    image: mysql:5.7

    # this is a fix to mysql on docker
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    
    #copy mysqldata from container to local volume
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
    